# Generated by Django 2.1.1 on 2018-09-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageCollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSearchPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, unique=True)),
                ('page', models.IntegerField()),
            ],
        ),
    ]
