# Generated by Django 2.1.1 on 2018-09-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageCollection', '0002_labelsearchpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabelSearchPage',
            new_name='LabelCurrentPage',
        ),
    ]
