# Generated by Django 2.1.1 on 2018-10-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageCollection', '0003_auto_20180926_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tags',
            new_name='tag',
        ),
    ]
